export { default as ErrorBoundary } from './error-boundary.vue'
export { default as VDialog } from './v-dialog.vue'
export { default as VSimpleTable } from './simple-table.vue'
export { default as VChips } from './chips.vue'
export { default as VLogo } from './v-logo.vue'
export { default as VButton } from './v-button.vue'
export * from './icons'
